version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - backend
  api-php:
    build: ./api-php/
    volumes:
      - ./api-php/src:/var/www/html
    ports:
      - 8000:8000
    networks:
      - backend
  api-node:
    build: ./api-node/
    volumes:
      - ./api-node/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8001:8001
    command: npm start
    networks:
      - backend
  api-python:
    build: ./api-python/
    volumes:
      - ./api-python/app:/app
    ports:
      - 8002:8002
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - LISTEN_PORT=8002
      - 'RUN=flask run --host=0.0.0.0 --port=8002'
    command: flask run --host=0.0.0.0 --port=8002
    networks:
      - backend
  proxy:
    image: nginx:alpine
    depends_on:
      - api-node
      - api-php
      - api-python
      - nextjs
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
  postgres:
    image: postgres:11-alpine
    volumes:
         - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=develop
    ports:
     - "5432:5432"
    networks:
     - backend

networks:
  backend:
    driver: "bridge"

volumes:
  node_modules: